import { useEffect, useState } from "react"
import { BrainCircuit, Briefcase, FileSearch, Landmark, RefreshCw, ShieldAlert, Target, Zap } from "lucide-react"
import { useAuth } from "@/context/AuthContext"
import { getLegalCases } from "@/services/aiWorkspaceService"
import { getAgentRuns, getLiveDossier, runLiveDossier } from "@/services/liveDossierService"

export default function LiveDossier() {
  const { user } = useAuth()
  const [cases,setCases]=useState<any[]>([]); const [caseId,setCaseId]=useState(""); const [dossier,setDossier]=useState<any>(null); const [runs,setRuns]=useState<any[]>([]); const [loading,setLoading]=useState(false)
  useEffect(()=>{ if(user?.id) getLegalCases(user.id).then(x=>{setCases(x); if(x[0]) setCaseId(x[0].id)}) },[user])
  useEffect(()=>{ if(user?.id&&caseId) Promise.all([getLiveDossier(user.id,caseId),getAgentRuns(user.id,caseId)]).then(([d,r])=>{setDossier(d);setRuns(r)}) },[user,caseId])
  async function analyze(){ if(!user?.id||!caseId)return; setLoading(true); try{const x=await runLiveDossier({userId:user.id,caseId});setDossier(x.dossier);setRuns(await getAgentRuns(user.id,caseId))}catch(e:any){alert(e?.message||"Erro ao construir Dossiê Vivo")}finally{setLoading(false)} }
  const selected=cases.find(c=>c.id===caseId)
  return <div className="min-h-screen bg-background text-foreground"><div className="max-w-7xl mx-auto p-6 lg:p-10 space-y-6">
    <section className="rounded-3xl border border-primary/30 bg-gradient-to-br from-primary/15 via-indigo-500/10 to-[#05050a] p-8"><div className="flex flex-col lg:flex-row justify-between gap-5"><div className="flex gap-4"><BrainCircuit className="text-primary" size={46}/><div><p className="text-xs uppercase tracking-[.25em] text-primary font-bold">NexJud Legal Operating System</p><h1 className="text-4xl font-black">Dossiê Vivo 2.0</h1><p className="text-muted-foreground mt-2">Fatos, provas, precedentes, risco e estratégia trabalhando como um único sistema.</p></div></div><div className="min-w-72 space-y-3"><select value={caseId} onChange={e=>setCaseId(e.target.value)} className="w-full rounded-xl bg-[#0f0f15] border border-border p-3">{cases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button onClick={analyze} disabled={loading||!caseId} className="w-full rounded-xl bg-primary py-3 font-black text-white flex justify-center gap-2"><RefreshCw size={18} className={loading?"animate-spin":""}/>{loading?"Agentes analisando...":"Atualizar inteligência"}</button></div></div></section>
    {!caseId?<Empty text="Cadastre um Caso Jurídico para iniciar o Dossiê Vivo."/>:!dossier?<Empty text={`O caso ${selected?.title||"selecionado"} ainda não possui Dossiê Vivo. Clique em Atualizar inteligência.`}/>:<>
      <section className="grid md:grid-cols-4 gap-4"><Metric label="Confiança" value={`${dossier.confidence_score||0}%`}/><Metric label="Fatos" value={String(dossier.facts?.length||0)}/><Metric label="Provas/Lacunas" value={String(dossier.evidence_map?.length||0)}/><Metric label="Próximas ações" value={String(dossier.next_best_actions?.length||0)}/></section>
      <Panel title="Síntese executiva" icon={<Briefcase/>}><p className="text-gray-300 whitespace-pre-line">{dossier.executive_summary||"Sem síntese."}</p></Panel>
      <section className="grid lg:grid-cols-2 gap-6"><Panel title="Case Analyst" icon={<FileSearch/>}><List items={dossier.facts} render={(x:any)=>x.fact||String(x)}/></Panel><Panel title="Evidence Analyst" icon={<ShieldAlert/>}><List items={dossier.evidence_map} render={(x:any)=>`${x.requirement}: ${x.evidence||"sem prova"} · força ${x.strength||"?"} · ${x.gap||"sem lacuna informada"}`}/></Panel><Panel title="Precedent Analyst" icon={<Landmark/>}><List items={dossier.precedent_map} render={(x:any)=>`${x.precedent}: ${x.applicability||"-"}${x.distinguishing?` · distinguishing: ${x.distinguishing}`:""}`}/></Panel><Panel title="Strategy Analyst" icon={<Target/>}><p className="text-gray-300">{dossier.strategy?.thesis||"Estratégia ainda não consolidada."}</p><div className="mt-4"><List items={dossier.risks} render={(x:any)=>`${x.level||""} — ${x.risk||x.reason||String(x)}`}/></div></Panel></section>
      <Panel title="Next Best Legal Action" icon={<Zap/>}><div className="space-y-3">{(dossier.next_best_actions||[]).map((x:any,i:number)=><div key={i} className="rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex gap-3"><span className="text-primary font-black">#{x.priority||i+1}</span><div><p className="font-bold">{x.action}</p><p className="text-sm text-muted-foreground mt-1">{x.why}</p>{x.depends_on&&<p className="text-xs text-gray-500 mt-2">Depende de: {x.depends_on}</p>}</div></div></div>)}</div></Panel>
      <section className="grid md:grid-cols-4 gap-3">{["case","evidence","precedent","strategy"].map(a=><div key={a} className="rounded-2xl border border-border bg-card p-4"><p className="text-xs text-primary uppercase font-black">Agent Layer</p><p className="font-bold capitalize mt-1">{a} Agent</p><p className="text-xs text-muted-foreground mt-2">{runs.some(r=>r.agent_type===a)?"Última execução registrada":"Aguardando execução"}</p></div>)}</section>
    </>}
  </div></div>
}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-border bg-card p-10 text-center text-muted-foreground">{text}</div>}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-primary/20 bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="text-3xl font-black text-primary mt-1">{value}</p></div>}
function Panel({title,icon,children}:{title:string,icon:React.ReactNode,children:React.ReactNode}){return <section className="rounded-2xl border border-border bg-card p-6"><div className="flex gap-2 items-center text-primary mb-4">{icon}<h2 className="text-xl font-bold text-foreground">{title}</h2></div>{children}</section>}
function List({items=[],render}:{items?:any[],render:(x:any)=>string}){return <div className="space-y-2">{items.length?items.map((x,i)=><div key={i} className="text-sm text-gray-300 flex gap-2"><span className="text-primary">•</span><span>{render(x)}</span></div>):<span className="text-muted-foreground">Nenhum item identificado.</span>}</div>}