import { useEffect, useMemo, useState } from "react"
import { BrainCircuit, BriefcaseBusiness, Database, GraduationCap, Landmark, Scale, ShieldAlert, Target, TrendingUp } from "lucide-react"
import { useAuth } from "@/context/AuthContext"
import { getOfficeIntelligence } from "@/services/officeIntelligenceService"

export default function OfficeIntelligence(){
  const { user } = useAuth()
  const [data,setData]=useState<any>(null)
  const [loading,setLoading]=useState(true)
  useEffect(()=>{if(!user?.id)return;setLoading(true);getOfficeIntelligence(user.id).then(setData).catch((e)=>alert(e?.message||"Erro ao carregar Office Intelligence")).finally(()=>setLoading(false))},[user])
  const outcomeRate=useMemo(()=>{if(!data?.metrics?.results)return 0;return Math.round((data.metrics.favorableResults/data.metrics.results)*100)},[data])
  if(loading)return <div className="p-8 text-muted-foreground">Construindo inteligência do escritório...</div>
  if(!data)return <div className="p-8 text-muted-foreground">Sem dados suficientes.</div>
  const m=data.metrics
  return <div className="min-h-screen bg-background text-foreground"><div className="max-w-7xl mx-auto p-6 lg:p-10 space-y-6">
    <section className="rounded-3xl border border-primary/30 bg-gradient-to-br from-primary/15 via-indigo-500/10 to-[#05050a] p-8"><div className="flex gap-4"><BrainCircuit className="text-primary" size={48}/><div><p className="text-xs uppercase tracking-[.25em] text-primary font-bold">NexJud Office Intelligence</p><h1 className="text-4xl font-black">Cérebro institucional do escritório</h1><p className="text-muted-foreground mt-2 max-w-3xl">Cruza casos, provas, riscos, decisões, resultados e aprendizados para transformar experiência dispersa em inteligência operacional reutilizável.</p></div></div></section>
    <section className="grid md:grid-cols-2 xl:grid-cols-5 gap-4"><Metric label="Casos" value={m.totalCases}/><Metric label="Casos analisados" value={m.analyzedCases}/><Metric label="Lacunas probatórias" value={m.evidenceGaps}/><Metric label="Memórias estratégicas" value={m.strategicMemories}/><Metric label="Resultados favoráveis" value={`${outcomeRate}%`}/></section>
    <section className="grid lg:grid-cols-2 gap-6"><Panel icon={<Scale/>} title="Questões jurídicas recorrentes"><Rank rows={data.rankings.issues}/></Panel><Panel icon={<ShieldAlert/>} title="Lacunas probatórias recorrentes"><Rank rows={data.rankings.evidenceRequirements}/></Panel><Panel icon={<Target/>} title="Riscos mais frequentes"><Rank rows={data.rankings.riskTypes}/></Panel><Panel icon={<Landmark/>} title="Tribunais mais presentes"><Rank rows={data.rankings.courts}/></Panel></section>
    <section className="grid lg:grid-cols-3 gap-6"><Panel icon={<GraduationCap/>} title="Memória estratégica"><p className="text-sm text-muted-foreground mb-4">{m.reusableMemories} aprendizados marcados como reutilizáveis.</p><div className="space-y-3">{data.memories.slice(0,6).map((x:any)=><div key={x.id} className="rounded-xl border border-border bg-black/20 p-4"><p className="font-bold">{x.issue||x.area||"Aprendizado"}</p><p className="text-sm mt-1">{x.lesson}</p><p className="text-xs text-muted-foreground mt-2">Confiança {x.confidence_score||0}% · reutilizável {x.reusable?"sim":"não"}</p></div>)}</div></Panel><Panel icon={<TrendingUp/>} title="Outcome Intelligence"><div className="grid grid-cols-2 gap-3"><Mini label="Decisões" value={m.decisions}/><Mini label="Resultados" value={m.results}/><Mini label="Favoráveis" value={m.favorableResults}/><Mini label="Parciais" value={m.partialResults}/><Mini label="Desfavoráveis" value={m.adverseResults}/><Mini label="Riscos altos" value={m.highRisks}/></div></Panel><Panel icon={<Database/>} title="Ativos de conhecimento"><p className="text-sm text-muted-foreground">O NexJud já possui uma base operacional composta por casos analisados, Dossiês Vivos, aprendizados estratégicos e impactos de precedentes.</p><div className="mt-4 space-y-2"><Mini label="Dossiês" value={data.dossiers.length}/><Mini label="Impactos de precedentes" value={data.impacts.length}/><Mini label="Casos ativos" value={m.activeCases}/></div></Panel></section>
    <Panel icon={<BriefcaseBusiness/>} title="O que o escritório está aprendendo"><div className="grid md:grid-cols-2 gap-4">{data.memories.filter((x:any)=>x.reusable).slice(0,10).map((x:any)=><div key={x.id} className="rounded-xl border border-primary/20 bg-primary/5 p-4"><p className="font-bold text-primary">{x.area||"Área não classificada"}</p><p className="text-sm mt-2">{x.lesson}</p>{x.result_summary&&<p className="text-xs text-muted-foreground mt-2">Resultado observado: {x.result_summary}</p>}</div>)}</div></Panel>
  </div></div>
}
function Metric({label,value}:{label:string,value:string|number}){return <div className="rounded-2xl border border-primary/20 bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="text-3xl font-black text-primary mt-1">{value}</p></div>}
function Panel({icon,title,children}:{icon:React.ReactNode,title:string,children:React.ReactNode}){return <section className="rounded-2xl border border-border bg-card p-6"><div className="flex gap-2 items-center text-primary mb-4">{icon}<h2 className="font-bold text-xl text-foreground">{title}</h2></div>{children}</section>}
function Rank({rows}:{rows:any[]}){return <div className="space-y-3">{rows.length?rows.map(([label,count]:[string,number],i:number)=><div key={label} className="flex items-center gap-3"><span className="w-7 h-7 rounded-full bg-primary/10 text-primary text-xs font-black flex items-center justify-center">{i+1}</span><span className="flex-1 text-sm capitalize">{label}</span><b>{count}</b></div>):<p className="text-muted-foreground text-sm">Ainda não há volume suficiente para ranking.</p>}</div>}
function Mini({label,value}:{label:string,value:string|number}){return <div className="rounded-xl border border-border bg-black/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="font-black text-lg">{value}</p></div>}
